---
- name: update package indices and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
  with_items: "{{ service_list }}"

